/*
This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import ru.bsuedu.cad.lab.impls.CategoryRequest;
import ru.bsuedu.cad.lab.intfs.Renderer;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;


public class App {
    public static void main(String[] args) {

        try (AnnotationConfigApplicationContext context = 
            new AnnotationConfigApplicationContext(AppConfig.class)) {

            Renderer renderer = context.getBean("dataBaseRenderer", Renderer.class);
            renderer.render();

            CategoryRequest request = context.getBean(CategoryRequest.class);
            request.execute();
        } catch (Exception e) {
            System.err.println("Application error: " + e.getMessage());
            e.printStackTrace(System.err);
            System.exit(1);
        }
    }
}
