/*
This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab.app;

import ru.bsuedu.cad.lab.config.AppConfigBasic;
import ru.bsuedu.cad.lab.config.AppConfigJpa;

import ru.bsuedu.cad.lab.renderer.Renderer;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;


public class App {
    public static void main(String[] args) {

        try (AnnotationConfigApplicationContext context = 
            new AnnotationConfigApplicationContext(AppConfigBasic.class, AppConfigJpa.class)) {
            
            Renderer renderer = context.getBean("dataBaseRenderer", Renderer.class);
            renderer.render();

            OrderClient orderClient = context.getBean(OrderClient.class);
            orderClient.createDemoOrder();
        } catch (Exception e) {
            System.err.println("Application error: " + e.getMessage());
            e.printStackTrace(System.err);
            System.exit(1);
        }
    }
}
